import type { Metadata } from "next";
import "./globals.css";
import TabBar from "@/components/home/TabBar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "jackson mall",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-[#f4f4f4]`}>
        {children}
        {/* 底部栏 */}
        <TabBar></TabBar>
        <Toaster position="top-center" duration={3000} />
      </body>
    </html>
  );
}
